= RHCEMD-Example

This repository holds the example application as a preparation for the RHCEMD (Red-Hat-Certified-Enterprise-Microservice-Developer) exam.

== Setup

This example is based on the Wildfly 22 application server.

IMPORTANT: You need to run the server with the `standalone-microprofile.xml` configuration.

== Microprofile

The following sections explain the setup and usage of the implement Microprofile specifications.

=== Health

Read link:https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.adoc[this] documentation about the wireformat and protocol health producer need to consider.

The readiness/liveness can be checked via the management endpoint and not via the application endpoint.

.Healthcheck endpoints
[source,bash]
----
# Readiness and Liveness Probes
http://localhost:9990/health

# Readiness Probes
http://localhost:9990/health/ready

# Liveness Probes
http://localhost:9990/health/live
----

=== Fault Tolerance

Read link:https://download.eclipse.org/microprofile/microprofile-fault-tolerance-1.1.2/microprofile-fault-tolerance-spec.html[this] doc about the fault tolerance specification and its relation ot other microprofile or Jakarta EE specifications such as CDI.

==== Timeout

The `@Timeout` annotation is a little tricky because it only works if the Thread

. waits for sometime,
. or the execution logic checks the interrupted state of the Thread it's executed on,
. and if the InterruptedException is not catched and ignored.

.Timeout example endpoints
[source,bash]
----
# A working example of the timeout handling
http://localhost:8080/rhcemd/api/timeout/working

# Illustrating the problem when a Threaqd doesn't wait and noone checks its interrupted state
http://localhost:8080/rhcemd/api/timeout/broken

# See how the annotations can be configured via microprofile-config
http://localhost:8080/rhcemd/api/timeout/configured
----

==== Retry

The `@Retry` annotation is pretty easy to use and to understand and doesn't have drawbacks as `@Timeout` has.

.Retry example endpoints
[source,bash]
----
# Retry works because error count < retryCount
http://localhost:8080/rhcemd/api/retry/working

# Retry doesn't work because fails to often
http://localhost:8080/rhcemd/api/retry/fail

# Retry doesn't work because an unsupported exception type is thrown
http://localhost:8080/rhcemd/api/retry/noRetry

# Retry works because a supported exception type is thrown
http://localhost:8080/rhcemd/api/retry/retryOnWorking

# Retry doesn't work because fails to often with a supported exception type
http://localhost:8080/rhcemd/api/retry/retryOnFail
----

==== Asynchronous

The `@Asynchronous` annotation executes methods on a different Thread but needs an active RequestContext.
`@Asynchronous` even allows us to use request scoped beans on another Thread which normally would cause a `ContextNotActiveException`.
So there if some kind o context propagation taking place.

There are limitations when using `Future` instead of `CompletionStage` as a return type of the async invoked methods.
`Future` doesn't allow chaining of executions, so if the future failed, then other fault-tolerance mechanisms such as `@Retry` won't work.
Only `CompletionStage` allows chaining, so if the `CompletionStage` failed, other fault-tolerance mechanisms can be invoked by chaining them on the failed `CompletionStage`.

.Asynchronous example endpoints
[source,bash]
----
# Asynchronous with CompletionStage working
http://localhost:8080/rhcemd/api/async/completionStage/working

# Asynchronous with CompletionStage fails with exception
http://localhost:8080/rhcemd/api/async/completionStage/fail

# Asynchronous with failed CompletionStage but working Retry
http://localhost:8080/rhcemd/api/async/completionStage/workingRetry

# Asynchronous with Future working
http://localhost:8080/rhcemd/api/async/future/working

# Asynchronous with Future fails with an exception
http://localhost:8080/rhcemd/api/async/future/fail

# Asynchronous with failed Future which breaks other fault-tolerance mechanisms such as Retry
http://localhost:8080/rhcemd/api/async/future/failedRetry
----
