= RHCEMD-Example

This repository holds the example application as a preparation for the RHCEMD (Red-Hat-Certified-Enterprise-Microservice-Developer) exam.

== Setup

This example is based on the Wildfly 22 application server.

IMPORTANT: You need to run the server with the `standalone-microprofile.xml` configuration.

== Microprofile

The following sections explain the setup and usage of the implement Microprofile specifications.

=== Health

Read link:https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.adoc[this] documentation about the wireformat and protocol health producer need to consider.

The readiness/liveness can be checked via the management endpoint and not via the application endpoint.

.Healthcheck endpoints
[source,bash]
----
# Readiness and Liveness Probes
http://localhost:9990/health

# Readiness Probes
http://localhost:9990/health/ready

# Liveness Probes
http://localhost:9990/health/live
----

=== Fault Tolerance

Read link:https://download.eclipse.org/microprofile/microprofile-fault-tolerance-1.1.2/microprofile-fault-tolerance-spec.html[this] doc about the fault tolerance specification and its relation ot other microprofile or Jakarta EE specifications such as CDI.

==== Timeout

The `@Timeout` annotation is a little tricky because it only works if the Thread

. waits for sometime,
. or the execution logic checks the interrupted state of the Thread it's executed on,
. and if the InterruptedException is not catched and ignored.

.Timeout example endpoints
[source,bash]
----
# A working example of the timeout handling
http://localhost:8080/rhcemd/api/timeout/working

# Illustrating the problem when a Threaqd doesn't wait and noone checks its interrupted state
http://localhost:8080/rhcemd/api/timeout/broken

# See how the annotations can be configured via microprofile-config
http://localhost:8080/rhcemd/api/timeout/configured
----