= RHCEMD-Example

This repository holds the example application as a preparation for the RHCEMD (Red-Hat-Certified-Enterprise-Microservice-Developer) exam.

== Setup

This example is based on the Wildfly 22 application server.

IMPORTANT: You need to run the server with the `standalone-microprofile.xml` configuration.

== Microprofile

The following sections explain the setup and usage of the implement Microprofile specifications.

=== Health

Read link:https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.adoc[this] documentation about the wireformat and protocol health producer need to consider.

The readiness/liveness can be checked via the management endpoint and not via the application endpoint.

.Healthcheck endpoints
[source,bash]
----
# Readiness and Liveness Probes
http://localhost:9990/health

# Readiness Probes
http://localhost:9990/health/ready

# Liveness Probes
http://localhost:9990/health/live
----

=== Fault Tolerance

Read link:https://download.eclipse.org/microprofile/microprofile-fault-tolerance-1.1.2/microprofile-fault-tolerance-spec.html[this] doc about the fault tolerance specification and its relation ot other microprofile or Jakarta EE specifications such as CDI.

==== Timeout

The `@Timeout` annotation is a little tricky because it only works if the Thread

. waits for sometime,
. or the execution logic checks the interrupted state of the Thread it's executed on,
. and if the InterruptedException is not catched and ignored.

.Timeout example endpoints
[source,bash]
----
# A working example of the timeout handling
http://localhost:8080/rhcemd/api/timeout/working

# Illustrating the problem when a Threaqd doesn't wait and noone checks its interrupted state
http://localhost:8080/rhcemd/api/timeout/broken

# See how the annotations can be configured via microprofile-config
http://localhost:8080/rhcemd/api/timeout/configured
----

==== Retry

The `@Retry` annotation is pretty easy to use and to understand and doesn't have drawbacks as `@Timeout` has.

.Retry example endpoints
[source,bash]
----
# Retry works because error count < retryCount
http://localhost:8080/rhcemd/api/retry/working

# Retry doesn't work because fails to often
http://localhost:8080/rhcemd/api/retry/fail

# Retry doesn't work because an unsupported exception type is thrown
http://localhost:8080/rhcemd/api/retry/noRetry

# Retry works because a supported exception type is thrown
http://localhost:8080/rhcemd/api/retry/retryOnWorking

# Retry doesn't work because fails to often with a supported exception type
http://localhost:8080/rhcemd/api/retry/retryOnFail
----

==== Asynchronous

The `@Asynchronous` annotation executes methods on a different Thread but needs an active RequestContext.
`@Asynchronous` even allows us to use request scoped beans on another Thread which normally would cause a `ContextNotActiveException`.
So there if some kind o context propagation taking place.

There are limitations when using `Future` instead of `CompletionStage` as a return type of the async invoked methods.
`Future` doesn't allow chaining of executions, so if the future failed, then other fault-tolerance mechanisms such as `@Retry` won't work.
Only `CompletionStage` allows chaining, so if the `CompletionStage` failed, other fault-tolerance mechanisms can be invoked by chaining them on the failed `CompletionStage`.

.Asynchronous example endpoints
[source,bash]
----
# Asynchronous with CompletionStage working
http://localhost:8080/rhcemd/api/async/completionStage/working

# Asynchronous with CompletionStage fails with exception
http://localhost:8080/rhcemd/api/async/completionStage/fail

# Asynchronous with failed CompletionStage but working Retry
http://localhost:8080/rhcemd/api/async/completionStage/workingRetry

# Asynchronous with Future working
http://localhost:8080/rhcemd/api/async/future/working

# Asynchronous with Future fails with an exception
http://localhost:8080/rhcemd/api/async/future/fail

# Asynchronous with failed Future which breaks other fault-tolerance mechanisms such as Retry
http://localhost:8080/rhcemd/api/async/future/failedRetry
----

==== Fallback

The `@Fallback` annotation is used to define fallback methods or handlers which provide a fallback result if a method fails.
When a method has a fallback method defined, then the fallback method must have the same signature as the method declaring the fallback.
When using a `FallbackHandler<T>` then we get an `ExecutionContext` provided which hold's

. the exception thrown,
. the method object which failed,
. and the parameters of the method invocation.

So the `FallbackHandler` handler is generic approach to provide a fallback result for any method signature, just the `FallbackHandler<T>` type parameter needs to be assignable to the actual method return type.

.Fallback example endpoints
[source,bash]
----
# Fallback working with a fallback method with no parameters
http://localhost:8080/rhcemd/api/fallback/method

# Fallback working with a fallback handler bean (unmanaged instance for each fallback)
http://localhost:8080/rhcemd/api/fallback/bean

# Fallback working with an supported thrown exception type (fallback method with parameters)
http://localhost:8080/rhcemd/api/fallback/applyOnWorking

# Fallback fails because an unsupported thrown exception type (fallback method with parameters)
http://localhost:8080/rhcemd/api/fallback/applyOnFail
----

==== CircuitBreaker

The `@CircuitBreaker` annotation is used to fail method calls fast, when the calls fail to often.
The circuit will be opened for the defined delay and half-close until a success threshold has been reached, and then closes again.

The implemented example illustrates the following scenario:

. Calls are made every 100 millis via a `Timer`
. The executions are repeated 50 times
. Call `1-5` and `21-25` fail with an exception
. The circuit is configured as `@CircuitBreaker(requestVolumeThreshold = 10, failureRatio = 0.5, successThreshold = 5, delay = 550, delayUnit = ChronoUnit.MILLIS)`

The result is:

. Calls `1-5`   fail with an intended exception
. Calls `6-10`  fail because of the circuit being open for 550 millis
. Calls `11-15` work because circuit is half-open
. Calls `16-20` work because circuit is closed
. Calls `21-25` fail because of an intended exception
. Calls `26-30` fail because of the circuit being open for 550 millis
. Calls `31-35` work because circuit is half-open
. Calls `36-50` work because circuit is closed


.CircuitBreaker example endpoints
[source,bash]
----
# Trigger the scenario
http://localhost:8080/rhcemd/api/circuitbreaker
----